package app.guohao.spareandroid;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.LinearLayout;

public class MainActivity extends Activity {

	int[] images = new int[] { R.drawable.splash };
	int currentImage = 0;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		//
		getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
				WindowManager.LayoutParams.FLAG_FULLSCREEN);
		//
		requestWindowFeature(Window.FEATURE_NO_TITLE);

		setContentView(R.layout.welcome);

		String appHome = Environment.getExternalStorageDirectory()
				.getAbsolutePath() + "/guohow";
		String subPath = appHome + "/NutterTools";

		MainActivity.createPath(appHome);
		MainActivity.createPath(subPath);

		File saveFile = new File(subPath, "nutter.log");
		try {
			FileWriter fw = new FileWriter(saveFile);
			BufferedWriter bw = new BufferedWriter(fw);

			bw.write("---auto generated by NutterTools---" + "\n" + "设备型号："
					+ "\n" + android.os.Build.MODEL + "\n" + "设备厂商：" + "\n"
					+ android.os.Build.MANUFACTURER
					+ "-------------------------");
			bw.close();
		} catch (Exception e) {
		}

		LinearLayout main = (LinearLayout) findViewById(R.id.splash);
		final ImageView image = new ImageView(this);
		main.addView(image);
		image.setImageResource(images[0]);
		image.setOnClickListener(new OnClickListener() {
			@Override
			public void onClick(View v) {

				Intent intent = new Intent();

				intent.setClass(MainActivity.this, warning.class);
				startActivity(intent);
				MainActivity.this.finish();

			}
		});

	}

	public static void createPath(String path) {

		File file = new

		File(path);

		if

		(!file.exists()) {

			file.mkdir();

		}

	}

}
