package app.guohao.spareandroid;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;

public class warning extends Activity {

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		requestWindowFeature(Window.FEATURE_NO_TITLE);
		setContentView(R.layout.warning);

		final Button bn = (Button) findViewById(R.id.login);

		bn.setOnClickListener(new OnClickListener() {

			@Override
			public void onClick(View source) {

				String appHome = Environment.getExternalStorageDirectory()
						.getAbsolutePath() + "/guohow_Soft";
				String subPath = appHome + "/NutterTools";

				createPath(appHome);
				createPath(subPath);

				File saveFile = new File(subPath, "nutter_Log.md");
				try {
					FileWriter fw = new FileWriter(saveFile);
					BufferedWriter bw = new BufferedWriter(fw);

					bw.write("---auto generated by NutterTools---" + "\n" + " "
							+ "\n" + android.os.Build.MODEL + "\n" + " " + "\n"
							+ android.os.Build.MANUFACTURER + "\n"
							+ "\n--copyright@guohow.app.android--");
					bw.close();
				} catch (Exception e) {
				}

				Intent intent = new Intent();

				intent.setClass(warning.this, homepage.class);
				startActivity(intent);
				// warning.this.finish();

			}
		});
	}

	public static void createPath(String path) {

		File file = new

		File(path);

		if

		(!file.exists()) {

			file.mkdir();

		}

	}

}
